spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/atcampus-db
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: atcampus-db