spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/atcampus-db}
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: atcampus-db