version: '3.9'
services:
  postgres-db:
    container_name: 'atcampus-postgres-db'
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=atcampus-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
